// Generated by scripts/find-pools.mjs — the deepest USDG pool per stock.
// Only stocks with real depth are listed; a stock with no entry is not tradable
// here and the UI must say so rather than quoting a price off an empty pool.

export const V3_FACTORY = "0x1f7d7550B1b028f7571E69A784071F0205FD2EfA" as const;

export interface StockPool {
  symbol: string;
  /** Deepest USDG pool — the one prices are read from. */
  pool: `0x${string}`;
  fee: number;
  /** Fee tier of a direct WETH pool with live liquidity, or null if none. */
  ethFee: number | null;
}

export const POOLS: StockPool[] = [
  { symbol: "NVDA", pool: "0xd4EB21209C4D6093f80B5b84f5C45cc093EA14a3", fee: 500, ethFee: 3000 },
  { symbol: "SPCX", pool: "0xEb07d9587eFD1778dFb9c385Ec43EF6d5F9fE401", fee: 3000, ethFee: null },
  { symbol: "USO", pool: "0x02175608F1b5E6b5ed221cCFdC7Be197D111D915", fee: 3000, ethFee: null },
  { symbol: "SLV", pool: "0x0Fa7BC480885DCf58Ad2ef63eC7289cF2481D51c", fee: 10000, ethFee: null },
  { symbol: "GME", pool: "0xE9713f453aDB9245B19559790c96F470a18F2fDF", fee: 10000, ethFee: 500 },
  { symbol: "SPY", pool: "0xA43b424Bc609495AED4BCD88d654934b510B0aD9", fee: 3000, ethFee: 500 },
  { symbol: "QQQ", pool: "0xEbD78dcfc8a6b3A696f1E191aD1ff321f9579f79", fee: 3000, ethFee: 3000 },
  { symbol: "TSLA", pool: "0xf4ACdAEEB7022862A763C9B1B885e11191c889E3", fee: 3000, ethFee: 3000 },
  { symbol: "COST", pool: "0x0a2121A50A09eD0796ae81F9c53fF9398355a398", fee: 3000, ethFee: null },
  { symbol: "AAPL", pool: "0x783C9bbB765047CFdD2b84b92b2Ca9F11D34b7Ed", fee: 3000, ethFee: 500 },
  { symbol: "NFLX", pool: "0xeA75eA625d83aE276b9ae8B0A3dC205916EE65cF", fee: 10000, ethFee: null },
  { symbol: "TSM", pool: "0x07e8Ea83D4C1340774c8965125e26e12bf943bf1", fee: 10000, ethFee: null },
  { symbol: "ASML", pool: "0xedb22516B14Eb2d1C86927Db373B0E8bF70F5cD1", fee: 10000, ethFee: null },
  { symbol: "PLTR", pool: "0x851680416A4f4E1c463d45171d61ACDdBc8554c0", fee: 3000, ethFee: null },
  { symbol: "INTC", pool: "0x2e5a92f5013a64661A49312111be2e8aBd33F56a", fee: 3000, ethFee: null },
  { symbol: "MSFT", pool: "0xeb60bCD1D920ad6E102690CCFC6fB488899E1510", fee: 3000, ethFee: null },
  { symbol: "SNDK", pool: "0xA1e1C9519cD5ae47e9A935645E1A7b935b944559", fee: 10000, ethFee: null },
  { symbol: "MU", pool: "0xd057B1Bc54917855BBee58eAd58647f47caB35E5", fee: 3000, ethFee: null },
  { symbol: "DELL", pool: "0xc30c89cB7815A1488b7998D15eEC73961707Fc5a", fee: 10000, ethFee: null },
  { symbol: "SGOV", pool: "0xfAb520051f96F4D2a32c22B6a3dD7fFfdf231bFe", fee: 3000, ethFee: null },
  { symbol: "GOOGL", pool: "0x553e9a453425CD9B90919F317061FbC3794CC57a", fee: 3000, ethFee: 500 },
  { symbol: "MSTR", pool: "0x17578C0e0D15da44f31677263114F71aE76653EA", fee: 10000, ethFee: 10000 },
  { symbol: "AMZN", pool: "0x8AC92DA74AB5F3b1d024Dc1943Ad7e15Dc4179Ef", fee: 3000, ethFee: null },
  { symbol: "QUBT", pool: "0x2E2a857C08aD6C09f1d1EC4FDB4Cc7cd06cF17f4", fee: 10000, ethFee: null },
  { symbol: "RDDT", pool: "0xa8744E76aED23B05F0126335E7BD38f7935D19fe", fee: 10000, ethFee: 10000 },
  { symbol: "AMD", pool: "0xD6aF1dcB75cdAE4F2efc403A58eF023A51edC686", fee: 10000, ethFee: null },
  { symbol: "RBLX", pool: "0x2ef5945cd5664876b6481FdacFaA2942995a4DA8", fee: 10000, ethFee: null },
  { symbol: "NU", pool: "0xb6d047637151f6De1d02028acdd187Aa9cb7AFE3", fee: 10000, ethFee: null },
  { symbol: "SMCI", pool: "0x9f0167dA6D9738b57CbA0833a541Db77762fB7Bb", fee: 10000, ethFee: null },
  { symbol: "SOFI", pool: "0xEA9368e1c88bCe7F04D16919eB131778A0dF826a", fee: 10000, ethFee: null },
  { symbol: "XLK", pool: "0xe20463635cEEEA8E30A315FFc4D4e81c80E53147", fee: 10000, ethFee: null },
  { symbol: "RDW", pool: "0x71E15C0Ed50142C772beE6195c936F04E4696F5d", fee: 10000, ethFee: null },
  { symbol: "BA", pool: "0xbf3904cAd0E63a4796CF806C21f2C1528B8eBE06", fee: 10000, ethFee: null },
  { symbol: "XOM", pool: "0x6aF79a2c154E7EeA9c87B38617D5f0B598B690FB", fee: 10000, ethFee: null },
  { symbol: "ZM", pool: "0x89eF54007B030a07B12F7cda9fe98cb278Cd7E6d", fee: 10000, ethFee: null },
  { symbol: "DDOG", pool: "0xb9a8b0A8a724f0813ceF2C9BfEf102087A33753E", fee: 10000, ethFee: null },
  { symbol: "LLY", pool: "0xF4274130137eeE20bAD928B593d992716516CEB9", fee: 10000, ethFee: null },
  { symbol: "PR", pool: "0xC2B5A8d6eCbbE9e4590271F7fE0261a3B265C3E7", fee: 10000, ethFee: null },
  { symbol: "ZS", pool: "0xdF9A23295D5D66E8066370CeA9349DEf9CcafDAe", fee: 10000, ethFee: null },
  { symbol: "LULU", pool: "0x19757223628dA89569f9A2488Af6C45cB9824EA1", fee: 10000, ethFee: null },
  { symbol: "AAOI", pool: "0x078c1690865964838Ae346077046750846a552D1", fee: 10000, ethFee: null },
  { symbol: "RKLB", pool: "0xa9888De1B9D64A93eaeb495A39FE9B3d00654928", fee: 10000, ethFee: null },
  { symbol: "F", pool: "0x01948e834623aA859ffDC0D299dD15e7C9D7486F", fee: 10000, ethFee: null },
  { symbol: "CCL", pool: "0xB19AcE635Ef3A28B85bFB01Bae97d0DE80750680", fee: 10000, ethFee: null },
  { symbol: "UPS", pool: "0x3Ab74C45DceCC6A62898204Dd42143a816B44CB1", fee: 10000, ethFee: null },
  { symbol: "CELH", pool: "0xe36DBdc0D6d5ab3182b6C18ba14B65BD676cCe02", fee: 10000, ethFee: null },
  { symbol: "LITE", pool: "0x48731d5732b6bD1AD3325C77cEDCFF131169783c", fee: 10000, ethFee: null },
  { symbol: "RGTI", pool: "0xb549D4EaF467277E48Aa350f216e413DF8c8BA12", fee: 10000, ethFee: null },
  { symbol: "SPMO", pool: "0x727C8A9e0da8Bb21bE322D2Bb5D891b126143b8C", fee: 10000, ethFee: null },
  { symbol: "MRVL", pool: "0x06cc0b96Be1fa1d754CE2e1228F5d8c616F795b0", fee: 10000, ethFee: null },
  { symbol: "QBTS", pool: "0x9eb22AD27148Cb90423422eC8A4a2ECF267E96bf", fee: 10000, ethFee: null },
];

export const poolFor = new Map(POOLS.map((p) => [p.symbol, p]));
